[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "cd backend && npm ci"
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd backend && npx prisma generate"
]

[start]
cmd = "node backend/dist/index.js"
