[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci && npm run build && npx prisma generate"

[deploy]
startCommand = "cd backend && npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
